import { BRAND } from '../../../constants/brand.constants';

export const loginStyles = {
  root: { display: 'flex', height: '100vh', width: '100%', bgcolor: '#f7f9fc' },
  leftPanel: {
    width: { xs: 0, md: '46%' },
    display: { xs: 'none', md: 'flex' },
    flexDirection: 'column',
    justifyContent: 'space-between',
    bgcolor: BRAND.red,
    p: 4,
    position: 'relative',
    overflow: 'hidden',
  },
  decorativeCircle: (size: number, top: number, right: number) => ({
    position: 'absolute',
    top,
    right,
    width: size,
    height: size,
    borderRadius: '50%',
    border: '1px solid rgba(255,255,255,0.08)',
    pointerEvents: 'none',
  }),
  logoArea: { display: 'flex', alignItems: 'center', gap: 1.5, zIndex: 1 },
  logoBox: { bgcolor: 'white', borderRadius: 2, p: 0.8, display: 'flex', alignItems: 'center', justifyContent: 'center' },
  logoIcon: { color: BRAND.red, fontSize: 22 },
  logoText: { color: 'white', fontWeight: 700, fontSize: 18 },
  heroContent: { zIndex: 1 },
  heroTitle: { color: 'white', fontWeight: 800, lineHeight: 1.3, mb: 2 },
  heroSub: { color: 'rgba(255,255,255,0.72)', fontSize: 14, lineHeight: 1.7, mb: 4 },
  chartBox: {
    borderRadius: 3,
    overflow: 'hidden',
    border: '1px solid rgba(255,255,255,0.15)',
    bgcolor: 'rgba(0,0,0,0.25)',
    height: 210,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chartBar: (i: number) => ({
    m: 1,
    bgcolor: 'rgba(255,255,255,0.1)',
    borderRadius: 1,
    height: 120 + i * 10,
    width: 60,
  }),
  securityRow: { display: 'flex', alignItems: 'center', gap: 1, zIndex: 1 },
  securityIcon: { color: 'rgba(255,255,255,0.6)', fontSize: 16 },
  securityText: { color: 'rgba(255,255,255,0.6)', fontSize: 12 },
  rightPanel: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    p: { xs: 3, md: 6 },
    bgcolor: 'white',
  },
  formWrapper: { flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center' },
  form: { width: '100%', maxWidth: 420 },
  formTitle: { mb: 0.5 },
  formSub: { color: 'text.disabled', fontSize: 14, mb: 3.5 },
  emailLabel: { fontSize: 13, fontWeight: 500, mb: 0.8 },
  emailRow: { display: 'flex', gap: 1, mb: 2.5 },
  atSign: { display: 'flex', alignItems: 'center', px: 1 },
  atText: { fontSize: 16, color: 'text.disabled' },
  passwordLabelRow: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 0.8 },
  passwordLabel: { fontSize: 13, fontWeight: 500 },
  forgotLink: { fontSize: 13, color: BRAND.red, fontWeight: 500 },
  passwordInput: { mb: 2.5 },
  rememberRow: { mb: 2.5 },
  checkbox: { color: BRAND.red, '&.Mui-checked': { color: BRAND.red } },
  rememberText: { fontSize: 13 },
  submitBtn: {
    bgcolor: BRAND.red,
    '&:hover': { bgcolor: BRAND.redDark },
    borderRadius: 2,
    fontWeight: 700,
    fontSize: 15,
    py: 1.4,
  },
  footer: { display: 'flex', justifyContent: 'center', gap: 3, pt: 2 },
  footerLink: { fontSize: 13, color: 'text.disabled' },
} as const;
