import { BRAND, SURFACE } from '../../../constants/brand.constants';

export const settingsStyles = {
  heroBanner: { borderRadius: '16px', overflow: 'hidden', mb: 0, position: 'relative' },
  heroBg: {
    height: 160,
    bgcolor: BRAND.red,
    backgroundImage: 'radial-gradient(circle at 20% 50%, rgba(255,255,255,0.07) 0%, transparent 60%), radial-gradient(circle at 80% 20%, rgba(0,0,0,0.15) 0%, transparent 50%)',
  },
  heroProfileRow: {
    bgcolor: '#fff',
    px: 3,
    pb: 2.5,
    borderBottom: `1px solid ${SURFACE.border}`,
  },
  heroInner: { display: 'flex', alignItems: 'flex-end', gap: 2.5, mt: '-48px' },
  avatarWrapper: { position: 'relative', flexShrink: 0 },
  avatar: {
    width: 100,
    height: 100,
    bgcolor: BRAND.red,
    fontSize: 32,
    fontWeight: 800,
    border: '4px solid #fff',
    boxShadow: '0 4px 16px rgba(0,0,0,0.15)',
  },
  editAvatarOverlay: {
    position: 'absolute',
    bottom: 4,
    right: 4,
    width: 26,
    height: 26,
    borderRadius: '50%',
    bgcolor: BRAND.red,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    border: '2px solid #fff',
  },
  profileInfo: { flex: 1, pb: 0.5 },
  profileNameRow: { display: 'flex', alignItems: 'center', gap: 1, flexWrap: 'wrap' },
  profileName: { fontWeight: 800, fontSize: 22, color: 'grey.900' },
  activeChip: { fontSize: 11, fontWeight: 700, bgcolor: '#DCFCE7', color: '#15803D', borderRadius: '6px' },
  inactiveChip: { fontSize: 11, fontWeight: 700, bgcolor: SURFACE.muted, color: '#6B7280', borderRadius: '6px' },
  profileRole: { fontSize: 13, color: 'grey.500', mt: 0.3 },
  exportBtnArea: { display: 'flex', gap: 1, pb: 0.5, flexShrink: 0 },
  exportBtn: {
    textTransform: 'none',
    fontSize: 12,
    borderRadius: '8px',
    borderColor: 'grey.300',
    color: 'grey.700',
    fontWeight: 600,
  },
  bodyGrid: { display: 'grid', gridTemplateColumns: { xs: '1fr', md: '300px 1fr' }, gap: 3, mt: 3 },
  panel: { border: `1px solid ${SURFACE.border}`, borderRadius: '14px', p: 2.5 },
  panelHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 2 },
  panelHeaderLeft: { display: 'flex', alignItems: 'center', gap: 1 },
  panelIconBox: {
    width: 28,
    height: 28,
    borderRadius: '50%',
    bgcolor: BRAND.redBg,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  panelIcon: { fontSize: 15, color: BRAND.red },
  panelTitle: { fontWeight: 700, fontSize: 14, color: 'grey.800' },
  editActionsRow: { display: 'flex', gap: 0.5 },
  editIconBtn: { color: BRAND.red },
  cancelIconBtn: { color: 'grey.500' },
  fieldLabel: { fontSize: 10, fontWeight: 700, color: 'grey.400', letterSpacing: '0.6px', mb: 0.4 },
  fieldInput: { fontSize: 13, borderRadius: '8px' },
  fieldValueLabel: { fontSize: 10, fontWeight: 700, color: 'grey.400', letterSpacing: '0.6px' },
  fieldValue: { fontSize: 13.5, color: 'grey.800', fontWeight: 500, mt: 0.2 },
  skillsChipBox: { display: 'flex', flexWrap: 'wrap', gap: 0.8 },
  skillChip: {
    fontSize: 12,
    fontWeight: 500,
    bgcolor: SURFACE.rowHeader,
    border: `1px solid ${SURFACE.border}`,
    borderRadius: '6px',
    color: 'grey.700',
  },
  statsRow: { display: 'flex', gap: 2 },
  statCard: {
    flex: 1,
    border: `1px solid ${SURFACE.border}`,
    borderRadius: '14px',
    p: 3,
    textAlign: 'center',
  },
  statIconBox: {
    width: 44,
    height: 44,
    borderRadius: '50%',
    bgcolor: BRAND.redBg,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    mx: 'auto',
    mb: 1.5,
  },
  statValue: { fontSize: 32, fontWeight: 800, color: 'grey.900', lineHeight: 1 },
  statLabel: { fontSize: 12, color: 'grey.500', mt: 0.5 },
  ongoingIcon: { fontSize: 20, color: BRAND.red },
  courseIconBox: {
    width: 38,
    height: 38,
    borderRadius: '10px',
    bgcolor: SURFACE.muted,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  courseTitle: { fontSize: 13.5, fontWeight: 600, color: 'grey.900' },
  courseSub: { fontSize: 12, color: 'grey.500' },
  coursePct: { fontSize: 13, fontWeight: 700, color: BRAND.red, flexShrink: 0, ml: 1 },
  progressBar: {
    height: 6,
    borderRadius: 4,
    bgcolor: SURFACE.muted,
    '& .MuiLinearProgress-bar': { bgcolor: BRAND.red, borderRadius: 4 },
  },
  achievementBox: { display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 0.8 },
  achievementIcon: {
    width: 56,
    height: 56,
    borderRadius: '14px',
    bgcolor: SURFACE.rowHeader,
    border: `1px solid ${SURFACE.border}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  achievementLabel: { fontSize: 11, color: 'grey.600', fontWeight: 500, textAlign: 'center' },
} as const;
