import { BRAND, SURFACE } from '../../../constants/brand.constants';

export const journeyStyles = {
  breadcrumb: { display: 'flex', alignItems: 'center', gap: 0.5, mb: 1 },
  breadcrumbLink: { fontSize: 13, color: 'grey.500', cursor: 'pointer', '&:hover': { color: BRAND.red } },
  breadcrumbActive: { fontSize: 13, color: 'grey.800', fontWeight: 600 },
  pageTitle: { color: 'grey.900' },
  pageSub: { color: 'grey.500', fontSize: 13, mt: 0.5 },
  card: {
    bgcolor: SURFACE.card,
    border: `1px solid ${SURFACE.border}`,
    borderRadius: '14px',
    p: 3,
    mb: 2,
    cursor: 'pointer',
    transition: 'box-shadow 0.2s, border-color 0.2s',
    '&:hover': { boxShadow: '0 4px 20px rgba(0,0,0,0.09)', borderColor: BRAND.red },
  },
  cardInner: { display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 3 },
  trackChip: { fontSize: 11, fontWeight: 700, bgcolor: BRAND.redBg, color: BRAND.red, borderRadius: '6px', letterSpacing: '0.4px', mb: 1.5 },
  cardTitle: { color: 'grey.900', mb: 1 },
  cardDesc: { fontSize: 13.5, color: 'grey.600', lineHeight: 1.7, maxWidth: 560 },
  metaChip: { fontSize: 12, bgcolor: SURFACE.muted, color: 'grey.700', borderRadius: '6px' },
  levelChip: (color: string, bg: string) => ({ fontSize: 12, fontWeight: 600, bgcolor: bg, color, borderRadius: '6px' }),
  progressBox: { minWidth: 180, textAlign: 'right' },
  progressLabel: { fontSize: 11, fontWeight: 700, color: 'grey.500', letterSpacing: '0.5px', mb: 0.5 },
  progressValue: { fontSize: 48, fontWeight: 900, color: BRAND.red, lineHeight: 1 },
  progressBar: {
    mt: 1.5,
    height: 6,
    borderRadius: 3,
    bgcolor: SURFACE.muted,
    '& .MuiLinearProgress-bar': { bgcolor: BRAND.red, borderRadius: 3 },
  },
  progressCountRow: { display: 'flex', alignItems: 'center', justifyContent: 'flex-end', gap: 0.5, mt: 0.8 },
  progressCountText: { fontSize: 12, color: 'grey.500' },
  decrementBtn: (disabled: boolean) => ({
    p: 0.3,
    color: disabled ? 'grey.300' : 'grey.500',
    '&:hover': { color: BRAND.red },
  }),
  incrementBtn: (disabled: boolean) => ({
    p: 0.3,
    color: disabled ? 'grey.300' : BRAND.red,
    '&:hover': { color: BRAND.redDark },
  }),
  modalBanner: { px: 3, pt: 3, pb: 2, borderBottom: `1px solid ${SURFACE.muted}` },
  modalTopRow: { display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 2 },
  modalOverallLabel: { fontSize: 12, fontWeight: 600, color: 'grey.500' },
  modalOverallPct: { fontSize: 12, fontWeight: 700, color: BRAND.red },
  modalProgressBar: {
    height: 6,
    borderRadius: 3,
    bgcolor: SURFACE.muted,
    '& .MuiLinearProgress-bar': { bgcolor: BRAND.red, borderRadius: 3 },
  },
  modalProgressSub: { fontSize: 12, color: 'grey.400', mt: 0.5 },
  courseListItem: { px: 3, py: 2, '&:hover': { bgcolor: 'grey.50' }, transition: 'background 0.15s' },
  completedChip: {
    fontSize: 11, fontWeight: 600, bgcolor: '#F0FDF4', color: '#16A34A', borderRadius: '6px', height: 20,
  },
  courseDuration: { fontSize: 11, bgcolor: SURFACE.muted, color: 'grey.600', borderRadius: '6px', height: 22 },
  courseLink: {
    fontSize: 12.5,
    color: BRAND.red,
    fontWeight: 600,
    textDecoration: 'none',
    display: 'flex',
    alignItems: 'center',
    gap: 0.3,
    '&:hover': { textDecoration: 'underline' },
  },
} as const;
