import { BRAND, SURFACE } from '../../../constants/brand.constants';

export const benchStyles = {
  statsRow: { display: 'flex', gap: 2, mb: 3 },
  statCard: (accent: string) => ({
    flex: 1,
    bgcolor: SURFACE.card,
    border: '1px solid',
    borderColor: 'grey.200',
    borderRadius: '12px',
    p: 2.5,
    borderTop: `3px solid ${accent}`,
  }),
  statLabel: { fontSize: 11, fontWeight: 700, color: 'grey.500', letterSpacing: '0.6px', mb: 1 },
  statValueRow: { display: 'flex', alignItems: 'baseline', gap: 1 },
  statValue: { fontSize: 28, fontWeight: 800, color: 'grey.900' },
  statSub: { fontSize: 13, color: 'grey.500' },
  tableWrapper: {
    bgcolor: SURFACE.card,
    border: '1px solid',
    borderColor: 'grey.200',
    borderRadius: '12px',
    overflow: 'hidden',
  },
  filterRow: {
    px: 2.5,
    py: 2,
    borderBottom: '1px solid',
    borderColor: 'grey.100',
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    flexWrap: 'wrap',
  },
  filterSelect: { fontSize: 13, borderRadius: '8px' },
  filterCount: { ml: 'auto', fontSize: 13, color: 'grey.500' },
  tableHeadRow: { bgcolor: SURFACE.rowHeader },
  tableHeadCell: { fontSize: 11, fontWeight: 700, color: 'grey.500', letterSpacing: '0.5px', py: 1.5, whiteSpace: 'nowrap' },
  subDeptHeaderCell: {
    py: 1,
    px: 2.5,
    bgcolor: `${BRAND.redBg}`,
    borderBottom: `1px solid ${BRAND.redBorder}`,
    borderTop: `1px solid ${BRAND.redBorder}`,
  },
  subDeptHeaderInner: { display: 'flex', alignItems: 'center', gap: 1.5 },
  subDeptHeaderText: { fontSize: 12, fontWeight: 800, color: BRAND.red, letterSpacing: '0.4px', textTransform: 'uppercase' as const },
  subDeptCountChip: { fontSize: 10, fontWeight: 700, bgcolor: BRAND.redBorder, color: BRAND.redDark, height: 18 },
  tableRow: { '&:last-child td': { border: 0 } },
  empCell: { py: 1.5 },
  empInner: { display: 'flex', alignItems: 'center', gap: 1.5 },
  empAvatar: { width: 38, height: 38, fontSize: 13, fontWeight: 700, bgcolor: SURFACE.muted, color: 'grey.700' },
  empName: { fontSize: 13.5, fontWeight: 700, color: 'grey.900' },
  empEmail: { fontSize: 12, color: 'grey.500' },
  empId: { fontSize: 13, color: 'grey.700', fontWeight: 500 },
  deptChip: { fontSize: 11, fontWeight: 700, bgcolor: SURFACE.muted, color: 'grey.600', borderRadius: '6px' },
  textMuted: { fontSize: 13, color: 'grey.700', fontWeight: 500 },
  courseStartedBtn: {
    textTransform: 'none',
    fontSize: 12,
    fontWeight: 600,
    color: '#1D4ED8',
    bgcolor: '#EFF6FF',
    borderRadius: '8px',
    border: '1px solid #BFDBFE',
    whiteSpace: 'nowrap',
    '&:hover': { bgcolor: '#DBEAFE' },
  },
  courseAssignedBtn: {
    textTransform: 'none',
    fontSize: 12,
    fontWeight: 600,
    color: '#16A34A',
    bgcolor: '#F0FDF4',
    borderRadius: '8px',
    border: '1px solid #BBF7D0',
    whiteSpace: 'nowrap',
    '&:hover': { bgcolor: '#DCFCE7' },
  },
  assignCourseBtn: {
    textTransform: 'none',
    fontSize: 12,
    fontWeight: 600,
    color: BRAND.red,
    bgcolor: BRAND.redBg,
    borderRadius: '8px',
    border: `1px solid ${BRAND.redBorder}`,
    whiteSpace: 'nowrap',
    '&:hover': { bgcolor: BRAND.redLight },
  },
  paginationBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    px: 2.5,
    py: 1.5,
    borderTop: '1px solid',
    borderColor: 'grey.100',
  },
  paginationSx: {
    '& .MuiPaginationItem-root.Mui-selected': {
      bgcolor: BRAND.red,
      color: '#fff',
      '&:hover': { bgcolor: BRAND.redDark },
    },
  },
  assignModal: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: { xs: '95vw', sm: '440px' },
    bgcolor: SURFACE.card,
    borderRadius: '16px',
    outline: 'none',
    p: 3,
  },
  assignModalHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 2 },
  assignTargetBox: {
    display: 'flex',
    alignItems: 'center',
    gap: 1.5,
    p: 1.5,
    bgcolor: SURFACE.rowHeader,
    borderRadius: '10px',
    mb: 2.5,
  },
  assignTargetAvatar: { width: 36, height: 36, fontSize: 13, fontWeight: 700, bgcolor: SURFACE.muted, color: 'grey.700' },
  searchDropdown: {
    px: 1.5,
    py: 1,
    position: 'sticky',
    top: 0,
    bgcolor: SURFACE.card,
    zIndex: 1,
    borderBottom: '1px solid #F0F0F0',
  },
  searchInnerBox: {
    display: 'flex',
    alignItems: 'center',
    gap: 1,
    px: 1,
    py: 0.6,
    border: `1px solid ${SURFACE.border}`,
    borderRadius: '8px',
    bgcolor: SURFACE.rowHeader,
  },
  assignBtn: {
    textTransform: 'none',
    bgcolor: BRAND.red,
    borderRadius: '8px',
    '&:hover': { bgcolor: BRAND.redDark },
    '&:disabled': { bgcolor: 'grey.200' },
  },
  cancelBtn: { textTransform: 'none', color: 'grey.600', borderRadius: '8px' },
  menuItemName: { fontSize: 13, fontWeight: 500 },
  menuItemSub: { fontSize: 11, color: 'grey.500' },
  emptyMenuText: { px: 2, py: 1.5, fontSize: 13, color: 'grey.400' },
  selectSx: (color: string, bg: string) => ({
    width: 140,
    fontSize: 12,
    fontWeight: 600,
    color,
    bgcolor: bg,
    '& .MuiOutlinedInput-notchedOutline': { border: 'none' },
    '& .MuiSelect-icon': { color },
  }),
  fieldLabel: { fontSize: 12, fontWeight: 600, color: 'grey.600', mb: 0.8 },
  assignActions: { display: 'flex', gap: 1.5, justifyContent: 'flex-end' },

  // Detail modal
  detailModal: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: { xs: '95vw', sm: '500px' },
    maxHeight: '90vh',
    overflowY: 'auto',
    bgcolor: SURFACE.card,
    borderRadius: '16px',
    outline: 'none',
    boxShadow: '0 20px 60px rgba(0,0,0,0.15)',
    p: 3,
  },
  detailHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    mb: 2.5,
    pb: 2,
    borderBottom: `1px solid ${SURFACE.border}`,
  },
  detailBanner: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 2,
    p: 2,
    bgcolor: SURFACE.rowHeader,
    border: `1px solid ${SURFACE.border}`,
    borderRadius: '12px',
    mb: 2.5,
  },
  detailAvatar: {
    width: 52,
    height: 52,
    fontSize: 16,
    fontWeight: 800,
    bgcolor: BRAND.redBg,
    color: BRAND.red,
    border: `2px solid ${BRAND.redBorder}`,
    flexShrink: 0,
  },
  detailGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 1.5,
    mb: 2,
  },
  detailField: {
    bgcolor: SURFACE.rowHeader,
    border: `1px solid ${SURFACE.border}`,
    borderRadius: '10px',
    px: 1.5,
    py: 1.2,
  },
  detailFieldLabel: {
    fontSize: 10,
    fontWeight: 700,
    color: 'grey.400',
    letterSpacing: '0.6px',
    textTransform: 'uppercase' as const,
    mb: 0.3,
  },
  detailFieldValue: {
    fontSize: 13,
    fontWeight: 600,
    color: 'grey.800',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  detailTechBox: {
    bgcolor: SURFACE.rowHeader,
    border: `1px solid ${SURFACE.border}`,
    borderRadius: '10px',
    px: 1.5,
    py: 1.2,
    mb: 2,
  },
  detailCourseRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 1.5,
  },
  detailCourseBox: (active: boolean) => ({
    bgcolor: active ? '#F0FDF4' : SURFACE.rowHeader,
    border: `1px solid ${active ? '#BBF7D0' : SURFACE.border}`,
    borderRadius: '10px',
    px: 1.5,
    py: 1.2,
  }),
};
