import { BRAND, SURFACE, ACCENT_COLORS } from '../../../constants/brand.constants';

export const dashboardStyles = {
  page: { width: '100%', minHeight: '100vh', bgcolor: SURFACE.page },
  welcomeBanner: {
    bgcolor: SURFACE.card,
    border: `1px solid ${SURFACE.border}`,
    borderRadius: '12px',
    p: 3,
    mb: 3,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 2,
  },
  systemChip: {
    bgcolor: '#F0FDF4',
    color: ACCENT_COLORS.green,
    fontWeight: 700,
    fontSize: 11,
    border: '1px solid #BBF7D0',
  },
  systemChipIcon: { fontSize: 14, color: `${ACCENT_COLORS.green} !important` },
  headerBtnRow: { display: 'flex', alignItems: 'center', gap: 2, flexWrap: 'wrap' },
  outlinedBtn: {
    textTransform: 'none',
    fontSize: 13,
    fontWeight: 600,
    color: 'grey.700',
    borderColor: 'grey.300',
    borderRadius: '8px',
  },
  containedBtn: {
    textTransform: 'none',
    fontSize: 13,
    fontWeight: 600,
    bgcolor: BRAND.red,
    borderRadius: '8px',
    '&:hover': { bgcolor: BRAND.redDark },
  },
  statGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(5, 1fr)',
    gap: 2,
    mb: 3,
    '@media (max-width:1100px)': { gridTemplateColumns: 'repeat(3,1fr)' },
    '@media (max-width:700px)': { gridTemplateColumns: 'repeat(2,1fr)' },
  },
  twoColGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 2,
    mb: 3,
    '@media (max-width:800px)': { gridTemplateColumns: '1fr' },
  },
  twoColGridBottom: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 2,
    '@media (max-width:800px)': { gridTemplateColumns: '1fr' },
  },
  card: {
    bgcolor: SURFACE.card,
    border: `1px solid ${SURFACE.border}`,
    borderRadius: '12px',
    p: 3,
  },
  cardHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    mb: 2.5,
  },
  cardTitle: { fontWeight: 700, fontSize: 15, color: 'grey.900' },
  viewReportLink: {
    fontSize: 13,
    fontWeight: 600,
    color: BRAND.red,
    cursor: 'pointer',
    '&:hover': { textDecoration: 'underline' },
  },
  deptRow: { mb: 2 },
  deptRowHeader: { display: 'flex', justifyContent: 'space-between', mb: 0.5 },
  deptName: { fontSize: 13, fontWeight: 600, color: 'grey.800' },
  deptPct: { fontSize: 13, fontWeight: 700, color: 'grey.700' },
  deptBar: {
    height: 7,
    borderRadius: 4,
    bgcolor: SURFACE.muted,
    '& .MuiLinearProgress-bar': { bgcolor: BRAND.red, borderRadius: 4 },
  },
  activityItem: { display: 'flex', gap: 1.5, mb: 2 },
  activityDot: { width: 8, height: 8, borderRadius: '50%', bgcolor: BRAND.red, mt: 0.6, flexShrink: 0 },
  activityText: { fontSize: 13, color: 'grey.700', lineHeight: 1.4 },
  activityTime: { fontSize: 11, color: 'grey.400', mt: 0.2 },
  benchChartRow: { display: 'flex', alignItems: 'center', gap: 3 },
  benchChartBox: { position: 'relative', width: 110, height: 110, flexShrink: 0 },
  benchChartCenter: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%,-50%)',
    textAlign: 'center',
  },
  benchChartValue: { fontSize: 20, fontWeight: 800, color: 'grey.900', lineHeight: 1 },
  benchChartLabel: { fontSize: 9, color: 'grey.500', fontWeight: 600 },
  benchGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 1.5, flex: 1 },
  quickActionsCol: { display: 'flex', flexDirection: 'column', gap: 1.5 },
  lastUpdatedRow: { display: 'flex', alignItems: 'center', justifyContent: 'flex-end', mt: 2, gap: 0.5 },
  lastUpdatedText: { fontSize: 11, color: 'grey.400' },
  loadingCenter: { display: 'flex', justifyContent: 'center', py: 4 },
  loadingSpinner: { color: BRAND.red },
} as const;
