import { BRAND, SURFACE } from '../../../constants/brand.constants';

export const hierarchyStyles = {
  overlay: {
    position: 'fixed' as const,
    inset: 0,
    background: 'rgba(0,0,0,0.5)',
    zIndex: 1300,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    p: { xs: 1, sm: 2 },
  },
  container: {
    background: '#F8F9FA',
    borderRadius: '20px',
    width: '95vw',
    maxWidth: 1100,
    height: '92vh',
    display: 'flex',
    flexDirection: 'column' as const,
    overflowY: 'auto' as const,
    boxShadow: '0 24px 80px rgba(0,0,0,0.25)',
    position: 'relative' as const,
  },
  topBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    px: 4,
    pt: 3,
    pb: 0.5,
    flexShrink: 0,
  },
  breadcrumb: {
    display: 'flex',
    alignItems: 'center',
    gap: 0.5,
  },
  breadcrumbText: {
    fontSize: 13,
    color: 'grey.500',
  },
  breadcrumbActive: {
    color: BRAND.red,
    fontWeight: 700,
    fontSize: 13,
  },
  header: {
    px: 4,
    pt: 1.5,
    pb: 2.5,
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 2,
    flexShrink: 0,
    borderBottom: '1px solid',
    borderColor: 'grey.200',
  },
  title: {
    fontWeight: 800,
    fontSize: 28,
    color: 'grey.900',
    lineHeight: 1.15,
  },
  subtitle: {
    fontSize: 13,
    color: 'grey.500',
    mt: 0.5,
  },
  headerBtns: {
    display: 'flex',
    gap: 1.5,
    alignItems: 'center',
    flexShrink: 0,
    mt: 0.5,
  },
  exportBtn: {
    textTransform: 'none' as const,
    fontSize: 13,
    fontWeight: 600,
    borderColor: 'grey.300',
    color: 'grey.700',
    borderRadius: '10px',
    height: 38,
    px: 2,
  },
  adjustBtn: {
    textTransform: 'none' as const,
    fontSize: 13,
    fontWeight: 600,
    borderRadius: '10px',
    background: BRAND.red,
    color: '#fff',
    height: 38,
    px: 2,
    '&:hover': { background: BRAND.redHover },
  },

  /* scrollable tree body */
  treeBody: {
    flex: 1,
    overflowY: 'auto' as const,
    overflowX: 'auto' as const,
    px: 4,
    py: 4,
  },
  treeInner: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    minWidth: 'max-content',
    mx: 'auto',
  },

  /* manager card */
  managerCard: {
    background: '#fff',
    border: `2px solid ${BRAND.red}`,
    borderRadius: '18px',
    p: '28px 32px',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    boxShadow: `0 6px 32px rgba(139,26,46,0.13)`,
    width: 280,
  },
  managerAvatar: {
    width: 80,
    height: 80,
    fontSize: 30,
    fontWeight: 800,
    background: `linear-gradient(135deg, ${BRAND.red} 0%, ${BRAND.redHover} 100%)`,
    color: '#fff',
    mb: 1.5,
  },
  managerName: {
    fontWeight: 800,
    fontSize: 18,
    color: 'grey.900',
    textAlign: 'center' as const,
  },
  managerRole: {
    fontWeight: 700,
    fontSize: 10,
    color: BRAND.red,
    letterSpacing: 1.2,
    textAlign: 'center' as const,
    mt: 0.4,
    textTransform: 'uppercase' as const,
  },
  cardDivider: {
    width: '85%',
    borderTop: '1px solid',
    borderColor: 'grey.200',
    my: 1.5,
  },
  infoRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 0.8,
    width: '100%',
    mt: 0.5,
  },
  infoText: {
    fontSize: 12,
    color: 'grey.600',
    wordBreak: 'break-all' as const,
  },

  /* connector lines */
  connectorArea: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    width: '100%',
  },
  vLine: {
    width: 2,
    background: `rgba(139,26,46,0.4)`,
    height: 40,
    borderRadius: 2,
  },
  hLineRow: {
    display: 'flex',
    alignItems: 'flex-start',
    position: 'relative' as const,
    width: '100%',
    justifyContent: 'center',
  },

  /* reportee cards row */
  reporteesRow: {
    display: 'flex',
    gap: '20px',
    justifyContent: 'center',
    flexWrap: 'nowrap' as const,
    mt: 0,
    px: 2,
  },
  reporteeWrap: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
  },
  reporteeVLine: {
    width: 2,
    height: 32,
    background: `rgba(139,26,46,0.4)`,
    borderRadius: 2,
  },
  reporteeCard: {
    background: '#fff',
    border: '1.5px solid',
    borderColor: 'grey.200',
    borderRadius: '16px',
    p: '20px 20px',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    width: 210,
    boxShadow: '0 2px 12px rgba(0,0,0,0.06)',
    flexShrink: 0,
  },
  reporteeAvatar: {
    width: 56,
    height: 56,
    fontSize: 20,
    fontWeight: 700,
    color: '#fff',
    mb: 1,
  },
  reporteeName: {
    fontWeight: 700,
    fontSize: 14,
    color: 'grey.900',
    textAlign: 'center' as const,
  },
  reporteeRole: {
    fontSize: 11,
    color: 'grey.500',
    textAlign: 'center' as const,
    mt: 0.3,
  },
  reporteeInfoRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 0.6,
    mt: 0.8,
    width: '100%',
    overflow: 'hidden',
  },
  reporteeInfoText: {
    fontSize: 11,
    color: 'grey.500',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  emptyState: {
    textAlign: 'center' as const,
    color: 'grey.400',
    fontSize: 14,
    py: 4,
  },

  /* stats footer */
  statsFooter: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: 2,
    mx: 4,
    mb: 3,
    mt: 0,
    borderTop: '1px solid',
    borderColor: 'grey.200',
    pt: 3,
    flexShrink: 0,
  },
  statCard: {
    background: '#F0F1F3',
    borderRadius: '14px',
    p: '16px 20px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 0.4,
  },
  statLabel: {
    fontSize: 10,
    fontWeight: 700,
    color: 'grey.500',
    letterSpacing: 0.8,
    textTransform: 'uppercase' as const,
  },
  statValue: {
    fontWeight: 800,
    fontSize: 22,
    color: 'grey.900',
    lineHeight: 1.2,
  },
  statValueRed: {
    fontWeight: 800,
    fontSize: 22,
    color: BRAND.red,
    lineHeight: 1.2,
  },
};
