import { BRAND, SURFACE } from '../../../constants/brand.constants';

export const usersStyles = {
  pageContainer: {
    width: '100%',
  },
  header: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    mb: 3,
  },
  exportBtn: {
    textTransform: 'none',
    fontSize: 13,
    borderColor: 'grey.300',
    color: 'grey.700',
    borderRadius: '8px',
    transition: 'all 0.18s',
    '&:hover': { borderColor: BRAND.red, color: BRAND.red, bgcolor: BRAND.redBg, transform: 'translateY(-1px)' },
  },
  addUserBtn: {
    textTransform: 'none',
    fontSize: 13,
    borderRadius: '8px',
    background: BRAND.red,
    boxShadow: 'none',
    transition: 'all 0.2s',
    '&:hover': { background: BRAND.redHover, transform: 'translateY(-1px)', boxShadow: `0 6px 20px rgba(139,26,46,0.28)` },
    '&:active': { transform: 'translateY(0)' },
  },
  filterCard: {
    background: SURFACE.card,
    border: '1px solid',
    borderColor: 'grey.200',
    borderRadius: '12px',
    p: 2.5,
    mb: 2.5,
    transition: 'box-shadow 0.2s',
    '&:hover': { boxShadow: '0 4px 16px rgba(0,0,0,0.05)' },
  },
  filterGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: '1fr 1fr 1fr auto' },
    gap: 2,
    alignItems: 'center',
  },
  filterSelect: { fontSize: 13, borderRadius: '8px' },
  filterLabel: { fontSize: 11, fontWeight: 600, color: 'grey.500', mb: 0.5 },
  clearFiltersBtn: {
    textTransform: 'none',
    fontSize: 13,
    color: BRAND.red,
    fontWeight: 600,
    whiteSpace: 'nowrap',
    mt: { xs: 0, sm: 2.5 },
    borderRadius: '8px',
    transition: 'all 0.18s',
    '&:hover': { bgcolor: BRAND.redBg },
  },
  tableCard: {
    background: SURFACE.card,
    border: '1px solid',
    borderColor: 'grey.200',
    borderRadius: '12px',
    overflow: 'hidden',
  },
  searchRow: {
    px: 2.5,
    py: 1.5,
    borderBottom: '1px solid',
    borderColor: 'grey.100',
    display: 'flex',
    alignItems: 'center',
    gap: 1,
  },
  tableHeadRow: { background: SURFACE.rowHeader },
  tableHeadCell: {
    fontSize: 11,
    fontWeight: 700,
    color: 'grey.500',
    letterSpacing: '0.5px',
    py: 1.5,
  },
  tableRow: {
    transition: 'background-color 0.16s',
    '&:hover': { bgcolor: BRAND.redBg },
    '&:last-child td': { border: 0 },
    '@keyframes rowIn': { from: { opacity: 0, transform: 'translateY(8px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
  },
  userCell: { py: 1.5 },
  userCellInner: { display: 'flex', alignItems: 'center', gap: 1.5 },
  avatar: {
    width: 38,
    height: 38,
    fontSize: 13,
    fontWeight: 700,
    bgcolor: SURFACE.muted,
    color: 'grey.700',
    transition: 'transform 0.18s',
    '&:hover': { transform: 'scale(1.08)' },
  },
  userName: { fontSize: 13.5, fontWeight: 600, color: 'grey.900' },
  userEmail: { fontSize: 12, color: 'grey.500' },
  deptChip: { fontSize: 12, bgcolor: SURFACE.muted, color: 'grey.700', borderRadius: '6px' },
  roleText: { fontSize: 13, color: 'grey.700' },
  statusRow: { display: 'flex', alignItems: 'center', gap: 0.7 },
  statusDot: (active: boolean) => ({ width: 7, height: 7, borderRadius: '50%', bgcolor: active ? '#15803D' : '#6B7280' }),
  statusText: (active: boolean) => ({ fontSize: 13, color: active ? '#15803D' : '#6B7280', fontWeight: 500 }),
  actionsBtns: { display: 'flex', gap: 0.5 },
  actionIconBtn: {
    transition: 'all 0.18s',
    '&:hover': { transform: 'scale(1.12)' },
  },
  paginationBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    px: 2.5,
    py: 1.5,
    borderTop: '1px solid',
    borderColor: 'grey.100',
  },
  paginationText: { fontSize: 13, color: 'grey.500' },
  paginationSx: {
    '& .MuiPaginationItem-root.Mui-selected': {
      bgcolor: BRAND.red,
      color: '#fff',
      '&:hover': { bgcolor: BRAND.redHover },
    },
  },
  editModal: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: { xs: '95vw', sm: '480px' },
    bgcolor: SURFACE.card,
    borderRadius: '16px',
    outline: 'none',
    p: 3,
  },
  editModalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    mb: 2.5,
  },
  editFieldLabel: { fontSize: 12, fontWeight: 600, color: 'grey.600', mb: 0.5 },
  editFieldInput: { fontSize: 13, borderRadius: '8px' },
  editStatusRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    mb: 3,
  },
  editStatusLabel: { fontSize: 13, fontWeight: 600, color: 'grey.700' },
  switchSx: {
    '& .MuiSwitch-switchBase.Mui-checked': { color: BRAND.red },
    '& .MuiSwitch-switchBase.Mui-checked + .MuiSwitch-track': { bgcolor: BRAND.red },
  },
  editActions: { display: 'flex', gap: 1.5, justifyContent: 'flex-end' },
  cancelBtn: { textTransform: 'none', color: 'grey.600', borderRadius: '8px' },
  saveBtn: {
    textTransform: 'none',
    bgcolor: BRAND.red,
    borderRadius: '8px',
    '&:hover': { bgcolor: BRAND.redHover },
  },
  addModal: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: { xs: '95vw', sm: '80vw', md: '760px' },
    maxHeight: '90vh',
    overflowY: 'auto',
    bgcolor: '#f7f9fc',
    borderRadius: '16px',
    outline: 'none',
    p: 3,
    '@keyframes modalIn': { from: { opacity: 0, transform: 'translate(-50%, -48%) scale(0.97)' }, to: { opacity: 1, transform: 'translate(-50%, -50%) scale(1)' } },
    animation: 'modalIn 0.22s ease',
  },
  addModalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    mb: 2,
  },
  deleteModal: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: { xs: '90vw', sm: '400px' },
    bgcolor: SURFACE.card,
    borderRadius: '16px',
    outline: 'none',
    p: 3.5,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    '@keyframes modalIn': { from: { opacity: 0, transform: 'translate(-50%, -48%) scale(0.97)' }, to: { opacity: 1, transform: 'translate(-50%, -50%) scale(1)' } },
    animation: 'modalIn 0.22s ease',
  },
  deleteIconWrap: {
    width: 64,
    height: 64,
    borderRadius: '50%',
    bgcolor: '#FFF1F2',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteActions: {
    display: 'flex',
    gap: 1.5,
    mt: 3,
    width: '100%',
  },
  deleteBtn: {
    flex: 1,
    bgcolor: BRAND.red,
    color: '#fff',
    borderRadius: '8px',
    textTransform: 'none',
    fontWeight: 600,
    '&:hover': { bgcolor: BRAND.redHover },
  },
} as const;
