import { BRAND, SURFACE } from '../../../constants/brand.constants';

const B = SURFACE.border;

export const courseRequestsStyles = {
  page: {
    p: { xs: 2, sm: 4 },
    bgcolor: SURFACE.page,
    minHeight: '100vh',
  },
  headerRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 2,
    flexWrap: 'wrap',
    mb: 3,
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: 1.5,
  },
  headerIconBox: {
    width: 38,
    height: 38,
    borderRadius: '10px',
    bgcolor: BRAND.redBg,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontWeight: 800,
    color: 'grey.900',
  },
  headerSubtitle: {
    color: 'grey.500',
    fontSize: 13,
  },
  statsRow: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr 1fr', sm: 'repeat(4, 1fr)' },
    gap: 1.5,
    mb: 3,
  },
  statCard: (accent: string) => ({
    display: 'flex',
    alignItems: 'center',
    gap: 1.4,
    p: 2,
    borderRadius: '14px',
    border: `1.5px solid ${B}`,
    bgcolor: '#fff',
    transition: 'transform 0.2s, box-shadow 0.2s, border-color 0.2s',
    '&:hover': { transform: 'translateY(-2px)', boxShadow: `0 8px 24px ${accent}22`, borderColor: accent },
  }),
  statIconBox: (accent: string) => ({
    width: 40,
    height: 40,
    borderRadius: '10px',
    bgcolor: `${accent}18`,
    color: accent,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  }),
  statValue: {
    fontWeight: 800,
    fontSize: 20,
    color: 'grey.900',
    lineHeight: 1.2,
  },
  statLabel: {
    fontSize: 11.5,
    fontWeight: 600,
    color: 'grey.500',
  },
  tableCard: {
    borderRadius: '16px',
    boxShadow: 'none',
    border: `1.5px solid ${B}`,
    overflow: 'hidden',
  },
  tableHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    px: 3,
    py: 2.2,
    borderBottom: `1px solid ${B}`,
    bgcolor: SURFACE.rowHeader,
  },
  tableHeaderTitle: {
    fontWeight: 700,
    color: 'grey.900',
    fontSize: 15.5,
  },
  tableHead: {
    bgcolor: SURFACE.rowHeader,
  },
  tableRow: {
    transition: 'background-color 0.16s',
    '&:hover': { bgcolor: BRAND.redBg },
    '&:last-child td, &:last-child th': { border: 0 },
    '@keyframes rowIn': { from: { opacity: 0, transform: 'translateY(8px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
  },
  tableCellHeader: {
    color: 'grey.500',
    fontWeight: 700,
    fontSize: '0.7rem',
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
  },
  tableTextBase: {
    color: 'grey.700',
    fontWeight: 500,
  },
  tableTextPrimary: {
    fontWeight: 700,
    color: 'grey.900',
  },
  avatarChip: {
    width: 32,
    height: 32,
    borderRadius: '50%',
    bgcolor: BRAND.redLight,
    color: BRAND.red,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 800,
    fontSize: '0.72rem',
    flexShrink: 0,
  },
  progressTrack: {
    width: '100%',
    maxWidth: 120,
    height: 6,
    borderRadius: 3,
    bgcolor: SURFACE.muted,
    overflow: 'hidden',
    mt: 0.5,
  },
  progressFill: (pct: number) => ({
    height: '100%',
    width: `${pct}%`,
    borderRadius: 3,
    background: `linear-gradient(90deg, ${BRAND.red}, ${BRAND.redHover})`,
    transition: 'width 0.5s ease',
  }),
  courseStartedChip: {
    fontWeight: 700,
    fontSize: '0.72rem',
    bgcolor: '#EFF6FF',
    color: '#1D4ED8',
    border: '1px solid #BFDBFE',
    borderRadius: '7px',
  },
  startCourseBtn: {
    textTransform: 'none',
    borderRadius: '8px',
    fontWeight: 700,
    fontSize: '0.75rem',
    borderColor: BRAND.redBorder,
    color: BRAND.red,
    transition: 'all 0.18s',
    '&:hover': { borderColor: BRAND.red, bgcolor: BRAND.redBg, transform: 'translateY(-1px)', boxShadow: `0 4px 12px ${BRAND.redBg}` },
  },
  statusChip: {
    fontWeight: 700,
    fontSize: '0.72rem',
    textTransform: 'capitalize',
    borderRadius: '7px',
  },
  emptyState: {
    borderRadius: '16px',
    boxShadow: 'none',
    border: `1px solid ${B}`,
    p: { xs: 5, sm: 8 },
    textAlign: 'center',
    background: `linear-gradient(145deg, ${BRAND.redBg} 0%, #fff 55%)`,
    '@keyframes fadeUp': { from: { opacity: 0, transform: 'translateY(20px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
    animation: 'fadeUp 0.4s ease',
  },
  submitBtn: {
    background: BRAND.red,
    color: '#fff',
    textTransform: 'none',
    fontWeight: 700,
    borderRadius: '10px',
    transition: 'all 0.2s',
    '&:hover': { background: BRAND.redHover, boxShadow: `0 6px 18px rgba(139,26,46,0.3)`, transform: 'translateY(-1px)' },
    '&:active': { transform: 'translateY(0)' },
    '&:disabled': { background: 'grey.300' },
  },
  assignEmployeeChip: { fontWeight: 700, bgcolor: BRAND.redBg, color: BRAND.red, border: `1px solid ${BRAND.redBorder}` },
  selectedCourseChip: { fontWeight: 700, bgcolor: BRAND.redBg, color: BRAND.red, border: `1px solid ${BRAND.redBorder}` },
  coordinatorChip: { fontWeight: 700, bgcolor: BRAND.redBg, color: BRAND.red, border: `1px solid ${BRAND.redBorder}` },
  dialogPaper: { borderRadius: '18px', width: 460, p: 0, overflow: 'hidden' },
  dialogTitle: {
    display: 'flex', justifyContent: 'space-between', alignItems: 'center',
    px: 3, py: 2.4,
    background: `linear-gradient(135deg, ${BRAND.redBg} 0%, #fff 70%)`,
    borderBottom: `1px solid ${B}`,
  },
  captionLabel: { mb: 0.5, display: 'block', fontWeight: 700, color: 'grey.500', fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.4 },
} as const;
