import { BRAND, SURFACE } from '../../../constants/brand.constants';

export const departmentsStyles = {
  tableCard: {
    background: SURFACE.card,
    border: '1px solid',
    borderColor: 'grey.200',
    borderRadius: '12px',
    overflow: 'hidden',
  },
  searchRow: {
    px: 2.5,
    py: 1.5,
    borderBottom: '1px solid',
    borderColor: 'grey.100',
    display: 'flex',
    alignItems: 'center',
    gap: 1,
  },
  tableHeadRow: { background: SURFACE.rowHeader },
  tableHeadCell: { fontSize: 11, fontWeight: 700, color: 'grey.500', letterSpacing: '0.5px', py: 1.5 },
  tableRow: {
    transition: 'background-color 0.16s',
    '&:hover': { bgcolor: BRAND.redBg },
    '&:last-child td': { border: 0 },
    '@keyframes rowIn': { from: { opacity: 0, transform: 'translateY(8px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
  },
  deptIconBox: {
    width: 36,
    height: 36,
    borderRadius: '8px',
    bgcolor: BRAND.redBg,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'transform 0.18s',
  },
  deptIcon: { color: BRAND.red, fontSize: 18 },
  actionIconBtn: {
    transition: 'all 0.18s',
    '&:hover': { transform: 'scale(1.12)' },
  },
  deptNameCell: {
    display: 'flex', alignItems: 'center', gap: 1.5,
    '&:hover > div:first-of-type': { transform: 'scale(1.08)' },
  },
  deptName: { fontSize: 13.5, fontWeight: 600, color: 'grey.900' },
  deptDesc: { fontSize: 13, color: 'grey.600' },
  deptManager: { fontSize: 13, color: 'grey.700', fontWeight: 500 },
  activeChip: { fontSize: 12, borderRadius: '6px', bgcolor: '#DCFCE7', color: '#15803D', fontWeight: 600 },
  inactiveChip: { fontSize: 12, borderRadius: '6px', bgcolor: SURFACE.muted, color: '#6B7280', fontWeight: 600 },
  dateText: { fontSize: 13, color: 'grey.500' },
  paginationBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    px: 2.5,
    py: 1.5,
    borderTop: '1px solid',
    borderColor: 'grey.100',
  },
  paginationText: { fontSize: 13, color: 'grey.500' },
  paginationSx: {
    '& .MuiPaginationItem-root.Mui-selected': {
      bgcolor: BRAND.red,
      color: '#fff',
      '&:hover': { bgcolor: BRAND.redHover },
    },
  },
  modal: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: { xs: '95vw', sm: '480px' },
    bgcolor: SURFACE.card,
    borderRadius: '16px',
    outline: 'none',
    p: 3,
    '@keyframes modalIn': { from: { opacity: 0, transform: 'translate(-50%, -48%) scale(0.97)' }, to: { opacity: 1, transform: 'translate(-50%, -50%) scale(1)' } },
    animation: 'modalIn 0.22s ease',
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    mb: 2.5,
  },
  deleteModal: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: { xs: '90vw', sm: '400px' },
    bgcolor: SURFACE.card,
    borderRadius: '16px',
    outline: 'none',
    p: 3.5,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    '@keyframes modalIn': { from: { opacity: 0, transform: 'translate(-50%, -48%) scale(0.97)' }, to: { opacity: 1, transform: 'translate(-50%, -50%) scale(1)' } },
    animation: 'modalIn 0.22s ease',
  },
  deleteIconWrap: {
    width: 64,
    height: 64,
    borderRadius: '50%',
    bgcolor: '#FFF1F2',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteActions: {
    display: 'flex',
    gap: 1.5,
    mt: 3,
    width: '100%',
  },
  cancelBtn: {
    flex: 1,
    borderColor: 'grey.300',
    color: 'grey.700',
    borderRadius: '8px',
    textTransform: 'none',
    fontWeight: 600,
    '&:hover': { borderColor: 'grey.400', bgcolor: 'grey.50' },
  },
  deleteBtn: {
    flex: 1,
    bgcolor: BRAND.red,
    color: '#fff',
    borderRadius: '8px',
    textTransform: 'none',
    fontWeight: 600,
    '&:hover': { bgcolor: BRAND.redHover },
  },
} as const;
